add user and item controllers
LuckaAa1988/java-shareit pull request #1
Opened 2024-05-18 08:54 UTC by LuckaAa1988

2024-05-18 18:19 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.

Вот все хорошо, но еще рекомендуют писать код так, чтобы он читался как обычный текст, то есть пусть у нас будут методы, имена которых нам принесут некоторую семантику в нашу систему, а не просто те же обращения к каким то массивам, мапам и пр,  посмотри на код с этой точки зрения :)

PS
Вот кстати ссылочка на почитать, правда про JS, но смысл тот же 
https://tproger.ru/articles/15-tips-selfdoc-js

2024-05-18 18:19 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userRepository.finById(userId).isPresent()) {
userRepository.exists(userId)

А если сделать вот такой метод, который нам вернет boolean, то кадетс что код станет более наглядным, давай сделаем? :)

finById => findById 
а тут похоже опечаточка небольшая кстати

2024-05-18 18:19 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +            User updatedUser = users.get(userId);
updatedUser

Не совсем тут понятно, переменная создается но потом у нас снова идут обращения к хранилищу, так и задумано, а далее ее использовать не получится? :)

Далее, кажется что стоит начать с того что, что разделить метод на логические части, сначала сделать проверку на то что пользователь редактирует свою запись, далее то что email указан, это проверяется в каждом if-е, кстати, то что он уникален, а далее уже обновляем поля, а не все сразу, как то так

2024-05-18 18:19 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    private List<String> emails = new ArrayList<>();
А нужна ли отдельная структура для хранения емейлов, в принципе же мы можем пробежаться по мапе и поиском проверять дубликат или нет. И для проверки уникальности тоже можно сделать отдельный метод, пригодиться ниже :)

2024-05-19 17:15 UTC, EugeneLenkevich approved these changes
Ну да, все норм. Единственное у Optional наверно не очень интересно дергать .get() и .isPresent() методы, зачем нам тогда он нужен если по факту это та же самая явная проверка на нулл, тут есть небольшая хитрость, чтобы понять которую надо немного поменять мышление. Optional нам дает возможность писать код без явных if-ов - проверок на null )

https://struchkov.dev/blog/ru/optional-in-java/

2024-05-19 17:15 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (findById(itemId).isPresent()) {
Обычно примерно вот так делают,  в более функциональном стиле :)

findById(itemId).ifPresent(item ->{
// тут логика работы с сущностью
})

2024-05-19 17:15 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemRepository.findById(itemId).isPresent()) {
А почему бы тут не вызвать exists вместо этого :)

2024-05-19 17:31 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (findById(itemId).isPresent()) {
Спасибо! попробую так

2024-05-19 17:39 UTC, merged