add bookings , comments
LuckaAa1988/java-shareit pull request #2
Opened 2024-06-01 10:27 UTC by LuckaAa1988

Большую часть кода написал по тестам постмана (от обратного) еще до открытия спринта , поэтому вопрос на сколько это имеет право на жизнь? :)

2024-06-01 17:54 UTC, EugeneLenkevich commented
> Большую часть кода написал по тестам постмана (от обратного) еще до открытия спринта , поэтому вопрос на сколько это имеет право на жизнь? :)

Более чем, а почему бы и нет :)

2024-06-01 18:12 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.
Все супер, смотрю используешь продвинутые техники типа того же  map-struct.
Но тут главное не переусложнить лишнего :)
Пару моментиков отметил

2024-06-01 18:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Transactional
@Transactional лучше поместить над методом сервиса, тут же один апдейт, он и так в транзакции выполнится (вроде как должен) на стороне СУБД, а вот в сервисе может быть несколько операций, которые хотелось бы чтобы выполнялись и откатывались в случае ошибки как одна логическая транзакция. Даже если в сервисе пока ничего нет, но вдруг появится потом :)

2024-06-01 18:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case ALL:
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2024-06-01 18:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingSpecification.java
> +    public static Specification<Booking> byBookerId(Long bookerId) {
А нужен ли тут Specification API, пусть конечно будет, но, в целом, он такой страшный и непонятный. Хотя бывает нужен для построения динамических запросов. В целом лучше обходиться именованными методами репозиториев и hql-запросами :)

2024-06-01 18:12 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return !userRepository.existsById(userId);
А есть ли смысл проверять еще раз после удаления, в принципе  метод deleteById может возвращать количество удаленных строк, можно это значение для проверки использовать, без доп запросов :)

2024-06-02 08:30 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Transactional
Я изначально пробовал без него вообще, но тогда статус не обновляется, и методом проб и ошибок нашёл что только если добавить @transactional конкретно над этим методом все работает :)  Сейчас попробовал над методом сервиса, такая же история - не обновляет, я немного в тупике :)

2024-06-02 08:32 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return !userRepository.existsById(userId);
Тут я сделал так только потому что, как оказалось, что если удалять по ID то метод возвращает void, а если например по имени то возвращает количество строк. Если есть какой то способ принудительно получить от него измененные строки ? 
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#deleteById(ID)

2024-06-02 13:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Transactional
Скорее всего нет транзакции активной по какой то причине, но тут надо уже сам код смотреть, как сам метод сервиса вызывается

2024-06-02 13:55 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return !userRepository.existsById(userId);
А вроде можно вот такой метод объявить

long deleteById(id)

ну или как то так
https://stackoverflow.com/questions/39796849/spring-repository-get-number-of-deleted-rows

2024-06-03 05:16 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Transactional
Да, вызывался из контроллера, ошибка была в другом, я зря менял статус у сущности вручную ) убрал и все заработало.

2024-06-03 05:16 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return !userRepository.existsById(userId);
спасибо!

2024-06-03 09:39 UTC, EugeneLenkevich approved these changes
Получилось стратегию применить, супер :)
А теперь наверно заметно что а) добавить обработку нового статуса стала гораздо проще, не надо лезть в основную логику б) обработка сосредоточена в одном месте и гораздо проще написать, например, тест конкретно на нее, он будет коротким и мы не волнуемся про остальную логику что была в том свиче

2024-06-03 09:39 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        log.info("Получен запрос на бронирование Item с id {} от USER c id {}",
Только на уровне сервиса мы уже оперируем глаголами предметной области, в сервисе нет ни запросов ни http, сервис вообще ничего не знает о том кто его вызывает :)

Вот как то так
log.info("Пользователь {} бронирует Item с id {}",...)

2024-06-03 15:12 UTC, merged