add itemRequests , add Unit tests
LuckaAa1988/java-shareit pull request #3
Opened 2024-06-16 21:31 UTC by LuckaAa1988

2024-06-18 16:18 UTC, EugeneLenkevich requested changes
Привет, Алексей! Спасибо за PR.

Пара моментиков
- давай все таки попробуем хотя бы в некоторых местах сделаем запросы через Pageale, посмотрим станет ли код станет проще (и тогда кстати не надо будет прописывать order by в запросах)
- попробуем оптимизировать объем запрашиваемых данных из бд :)

2024-06-18 16:18 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        var item = itemRepository.saveAndFlush(ItemMapper.INSTANCE.fromDto(itemCreate, user, itemRequest));
ItemMapper.INSTANCE.fromDto

А маппер вроде же можно как спринговый бин инжектить :)

![image](https://github.com/LuckaAa1988/java-shareit/assets/109306643/06946895-4f5b-41c1-b279-cea172af6626)

2024-06-18 16:18 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        var items = itemRepository.findAll();
var items = itemRepository.findAll();

А если количество items  в БД, как это обычно бывает, достаточно велико, то не словим ли мы OutOfMemoryException, а нельзя ли тут вытаскивать только ту небольшую часть данных которая нам нужна в данный момент? :)

2024-06-18 16:18 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        var items = itemRepository.findAll();
Опять таки, ниже мы фильтруем записи, а неьзя ли сразу отсечь лишнее и запросом достать только то что надо? А потом уже и результат в dto перегонять. Иначе у нас будь то бы много лишних действий получается, а это и лишняя нагрузка  и код труднее читать :)

2024-06-18 17:21 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAll(Long bookerId, Integer from, Integer size);
Я изначально так и сделал, но с Pageable у меня не проходил Postman тест вот этот: /bookings?from=4&size=2
Он почему то не хочет выводить 2 бронирования, как просит тест - выдаёт пустой список ,я с этим пытался бороться, но в итоге решил сделать так как сейчас.
Я проверил если в Pageable указать size больше чем осталось элементов в списке и если их считает не с 0(from) , то выдаёт пустой список, как с этим бороться?

2024-06-19 14:24 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAll(Long bookerId, Integer from, Integer size);
Оказалось все проще, я просто неправильно рассчитывал page ;)

2024-06-20 05:00 UTC, LuckaAa1988 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        var item = itemRepository.saveAndFlush(ItemMapper.INSTANCE.fromDto(itemCreate, user, itemRequest));
Заинжектил как бин, но упали все тесты :) так как теперь надо мокать Маппер и вручную писать что он возвращает, может есть способ заставить его работать когда делаешь юнит тесты в сервисе слое, где много обращений к мапперу  ?

2024-06-21 14:17 UTC, merged